name: rinha-2025

# max
# cpu=1.5
# mem=350MB

x-service-templates:
  load-balancer: &load-balancer
    image: nginx:1.29-alpine3.22-slim
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor

  database: &database
    image: postgres:17.5-alpine3.22
    networks:
      - rinha-net
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=UTC
      - POSTGRES_DB=rinha_2025
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres
      -c max_connections=18
      -c shared_buffers=32MB
      -c work_mem=8MB
      -c effective_cache_size=128MB
      -c synchronous_commit=off
      -c fsync=off
      -c full_page_writes=off
      -c autovacuum=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c log_min_messages=fatal
      -c wal_writer_delay=1000ms
      -c commit_delay=100
#    command: postgres -c timezone=UTC -c max_connections=30 -c shared_buffers=16MB -c effective_cache_size=100MB -c work_mem=8MB -c maintenance_work_mem=16MB -c synchronous_commit=off -c fsync=off -c wal_buffers=4MB -c checkpoint_timeout=600 -c max_wal_size=4096 -c commit_delay=100 -c full_page_writes=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha_2025"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 6s

  backend-application: &backend-application
    image: rinha-2025-backend:1.0.0
    environment:
      - SERVER_PORT=8080
      - PAYMENT_API_SUMMARY_DELAY=500
      - PAYMENT_API_ASYNC_INPUT=false

      - DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - DEFAULT_PAYMENT_PROCESSOR_READ_TIMEOUT=7000

      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
      - FALLBACK_PAYMENT_PROCESSOR_READ_TIMEOUT=10000

      - DB_URL=jdbc:postgresql://backend-database:5432/rinha_2025
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

      - DB_POOL_MINIMUM_SIZE=5
      - DB_POOL_MAXIMUM_SIZE=9
      - DB_POOL_IDLE_TIMEOUT=30000

      # payment processor selection
      - PAYMENT_PROCESSOR_SELECTION_DEFAULT_ADVANTAGE=0.2
      - PAYMENT_PROCESSOR_SELECTION_SCHEDULER_INTERVAL_MS=200
      - PAYMENT_PROCESSOR_SELECTION_SCHEDULER_INITIAL_DELAY_MS=1000

      # health check update cache
      - HEALTH_CHECK_CACHE_SCHEDULER_INITIAL_DELAY_MS=1000
      - HEALTH_CHECK_CACHE_SCHEDULER_INTERVAL_MS=500

      # payment processor
      - PAYMENT_PROCESSOR_MAX_QUANTITY=250
      - PAYMENT_PROCESSOR_THREAD_POOL_SIZE=2
      - PAYMENT_PROCESSOR_THREAD_INTERVAL_EXECUTION_MS=900
      - PAYMENT_PROCESSOR_CONCURRENCY_TYPE=parallel_vt
#      - PAYMENT_PROCESSOR_SCHEDULER_INTERVAL_MS=200
#      - PAYMENT_PROCESSOR_SCHEDULER_INITIAL_DELAY_MS=1000

      # payment confirmation
      - PAYMENT_CONFIRMATION_MAX_QUANTITY=250
      - PAYMENT_CONFIRMATION_THREAD_POOL_SIZE=2
      - PAYMENT_CONFIRMATION_THREAD_INTERVAL_EXECUTION_MS=1000
      - PAYMENT_CONFIRMATION_PERSISTENCE_COPY_THRESHOLD=500
      - PAYMENT_CONFIRMATION_NUMBER_OF_RETRIES=1
      - PAYMENT_CONFIRMATION_INTERVAL_RETRIES_EXECUTION_MS=20
#      - PAYMENT_CONFIRMATION_SCHEDULER_INITIAL_DELAY_MS=1000
#      - PAYMENT_CONFIRMATION_SCHEDULER_INTERVAL_MS=200
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      database:
        condition: service_healthy

services:
  database:
    <<: *database
    container_name: rinha-backend-db
    hostname: backend-database
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  load-balancer:
    <<: *load-balancer
    hostname: nginx
    container_name: load-balancer
    depends_on:
      - backend01
      - backend02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  backend01:
    <<: *backend-application
    hostname: backend-instance-01
    container_name: backend-instance-01
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  backend02:
    <<: *backend-application
    hostname: backend-instance-02
    container_name: backend-instance-02
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
