name: rinha-2025

# max
# cpu=1.5
# mem=350MB

x-service-templates:
  load-balancer: &load-balancer
    image: nginx:1.29-alpine3.22-slim
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor

  database: &database
    image: postgres:17.5-alpine3.22
    networks:
      - rinha-net
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=UTC
      - POSTGRES_DB=rinha_2025
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c timezone=UTC -c max_connections=40 -c shared_buffers=32MB -c effective_cache_size=100MB -c work_mem=2MB -c maintenance_work_mem=16MB -c synchronous_commit=off -c fsync=off -c wal_buffers=1MB -c commit_delay=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha_2025"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend-application: &backend-application
    image: rinha-2025-backend:0.0.2
    environment:
      - SERVER_PORT=8080

      - DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - DEFAULT_PAYMENT_PROCESSOR_READ_TIMEOUT=5000

      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
      - FALLBACK_PAYMENT_PROCESSOR_READ_TIMEOUT=10000

      - DB_URL=jdbc:postgresql://backend-database:5432/rinha_2025?stringtype=unspecified
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

      - DB_POOL_MINIMUM_SIZE=10
      - DB_POOL_MAXIMUM_SIZE=20
      - DB_POOL_IDLE_TIMEOUT=30000

      - OUTBOX_PROCESSOR_PULL_MAX_AMOUNT=50
      - OUTBOX_PROCESSOR_SCHEDULER_INTERVAL_MS=300
      - OUTBOX_PROCESSOR_SCHEDULER_INITIAL_DELAY_MS=3000
      - PAYMENT_PROCESSOR_CONCURRENCY_TYPE=parallel_vt

      - OUTBOX_CLEANER_SCHEDULER_INTERVAL_MS=10000
      - OUTBOX_CLEANER_SCHEDULER_INITIAL_DELAY_MS=5000
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      database:
        condition: service_healthy

services:
  load-balancer:
    <<: *load-balancer
    hostname: nginx
    container_name: load-balancer
    depends_on:
      - backend01
      - backend02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  database:
    <<: *database
    container_name: rinha-backend-db
    hostname: backend-database
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  backend01:
    <<: *backend-application
    hostname: backend-instance-01
    container_name: backend-instance-01
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "90MB"

  backend02:
    <<: *backend-application
    hostname: backend-instance-02
    container_name: backend-instance-02
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "90MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
