name: rinha-2025

# max
#   cpu=1.5
#   mem=350MB

x-service-templates:
  load-balancer: &load-balancer
    image: nginx:1.29-alpine3.22-slim
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor

  database: &database
    image: postgres:17.5-alpine3.22
    networks:
      - rinha-net
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=UTC
      - POSTGRES_DB=rinha_2025
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres
      -c max_connections=20
      -c shared_buffers=32MB
      -c work_mem=8MB
      -c effective_cache_size=128MB
      -c synchronous_commit=off
      -c fsync=off
      -c full_page_writes=off
      -c autovacuum=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c log_min_messages=fatal
      -c wal_writer_delay=1000ms
      -c commit_delay=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha_2025"]
      interval: 3s
      timeout: 3s
      retries: 2
      start_period: 6s

  backend-application: &backend-application
    image: rinha-2025-backend:1.1.0
    environment:
      - SERVER_PORT=8080
      - UNDERTOW_CUSTOMIZER=true
      - UNDERTOW_THREADS_IO=2
      - UNDERTOW_THREADS_WORKER=15
      - UNDERTOW_BUFFER_SIZE=8192
      - UNDERTOW_DIRECT_BUFFERS=true

      - LOGGING_LEVEL=OFF
      - PAYMENT_API_SUMMARY_DELAY=50
      - PAYMENT_API_ASYNC_INPUT=true
      - PAYMENT_API_FILTER_PROCESS=false

      - JACKSON_INSTALL_AFTERBURNER=true
      - JACKSON_DISABLE_DEFAULT_FEATURES=true

      - DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - DEFAULT_PAYMENT_PROCESSOR_READ_TIMEOUT=30000

      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
      - FALLBACK_PAYMENT_PROCESSOR_READ_TIMEOUT=30000

      - DB_URL=jdbc:postgresql://backend-database:5432/rinha_2025
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

      - DB_POOL_MINIMUM_SIZE=8
      - DB_POOL_MAXIMUM_SIZE=15
      - DB_POOL_IDLE_TIMEOUT=30000

      # health check
      - HEALTH_CHECK_EXECUTION_SCHEDULER_INTERVAL=500
      - HEALTH_CHECK_CACHE_SCHEDULER_INTERVAL=500

      # payment processor selection
      - PAYMENT_PROCESSOR_SELECTION_SCHEDULER_INTERVAL=200
      - PAYMENT_PROCESSOR_SELECTION_FALLBACK_ENABLED=true
      - PAYMENT_PROCESSOR_SELECTION_DEFAULT_ADVANTAGE_THRESHOLD=450
      - PAYMENT_PROCESSOR_SELECTION_DEFAULT_ADVANTAGE=0.8
      - PAYMENT_PROCESSOR_SELECTION_USE_DEFAULT_WHEN_LESS=450

      # payment processor
      - PAYMENT_PROCESSOR_WORKER=1
      - PAYMENT_PROCESSOR_WORKER_INTERVAL=1
      - PAYMENT_PROCESSOR_QUEUE_LENGTH=150000
      - PAYMENT_PROCESSOR_MAX_DEQUEUE=50
      - PAYMENT_PROCESSOR_SEMAPHORE_MAX_CONCURRENCY=80
      - PAYMENT_PROCESSOR_MAX_RETRIES=6
      - PAYMENT_PROCESSOR_MAX_QUANTITY_REDUCTION_PERCENTAGE=0.95
      - PAYMENT_PROCESSOR_EXTRA_WORKER_INTERVAL=50

      # payment processed
      - PAYMENT_PROCESSED_WORKER=1
      - PAYMENT_PROCESSED_WORKER_INTERVAL=200
      - PAYMENT_PROCESSED_QUEUE_LENGTH=150000
      - PAYMENT_PROCESSED_MAX_DEQUEUE=1000
      - PAYMENT_PROCESSED_MAX_RETRIES=2

      # payment persistence
      - PAYMENT_PERSISTENCE_INDIVIDUAL_THRESHOLD=5
      - PAYMENT_PERSISTENCE_COPY_THRESHOLD=400
    networks:
      - rinha-net
      - payment-processor
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      database:
        condition: service_healthy

services:
  database:
    <<: *database
    container_name: rinha-backend-db
    hostname: backend-database
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  load-balancer:
    <<: *load-balancer
    hostname: nginx
    container_name: load-balancer
    depends_on:
      - backend01
      - backend02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  backend01:
    <<: *backend-application
    hostname: backend-instance-01
    container_name: backend-instance-01
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  backend02:
    <<: *backend-application
    hostname: backend-instance-02
    container_name: backend-instance-02
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
